functional:
  - Пользователь должен иметь возможность решать задачи на скорость против другого игрока
  - Пользователь должен иметь возможность регистрации и авторизации на сайте
  - Оба игрока должны иметь возможность менять язык программирования во время решения
  - Пользователь должен иметь возможность играть с любым человеком, с ботом или другом (игра должна быть доступна по ссылке)
  - Пользователь должен иметь возможность выбрать игру по уровню сложности. При создании игры можно выбрать определенную игру, иначе она будет подобрана наугад
  - Другие пользователи должны иметь возможность следить за ходом игры
  - В игре должен быть чат, в котором будут общаться зарегистрированные пользователи
  - Завершенная игра должна быть доступна в записи
non-functional:
  - Задачи должны быть даны на двух языках — русском и английском
  - Пользователи должны получать очки, на основе которых будет строится рейтинг за неделю, месяц и за все время
  - Редактор для ввода кода должен выглядеть как проигрыватель. Оба игрока видят два редактора: слева - свой редактор, справа - соперника. Каждый игрок видит код своего соперника в режиме он-лайн, вывод тестов
  - Сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен быть удобным на мобильном устройстве
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров
  - Сайт должен быть способен обрабатывать большое количество трафика (например, 1000 одновременных пользователей)
implicit:
  - сообщения в чате должны проходить автоматическую модерацию
  - сайт должен соответствовать законодательству 
